#!/bin/bash

#  _       _ _   
# (_)_ __ (_) |_ 
# | | '_ \| | __|
# | | | | | | |_ 
# |_|_| |_|_|\__|
# ps: all fontart generated by figlet               
# import all functions
source ./lib/*.sh
check-root
check-ubuntu
#   ___ _ ____   __
#  / _ \ '_ \ \ / /
# |  __/ | | \ V / 
#  \___|_| |_|\_/  
                 
# proxy conf for specific network environments
# please use 
#
# -R 12321:127.0.0.1:7890
#
# in your ssh command
function set_proxy(){
  export ProIP="http://127.0.0.1:12321"
  export http_proxy=$"$ProIP"
  export https_proxy=$"$ProIP"
  cp ./share/apt/apt.conf.d/99-proxy.conf /etc/apt/apt.conf.d/
}
#====
# uncomment this if you need proxy
#set_proxy
#====

# domain config
# please change this
export DOMAIN=example.com
export Working_DIR=$(pwd)
# cloudflare cert setting
export dns_cloudflare_email=email@example.com
export dns_cloudflare_api_key=yourapikey

#  _     _   _ __  __ ____  
# | |   | \ | |  \/  |  _ \ 
# | |   |  \| | |\/| | |_) |
# | |___| |\  | |  | |  __/ 
# |_____|_| \_|_|  |_|_|   
LNMP-base
LNMP-mediawiki
#LNMP-mytinytodo
#LNMP-nextcloud
#LNMP-phpmyadmin

#      _            _             
#   __| | ___   ___| | _____ _ __ 
#  / _` |/ _ \ / __| |/ / _ \ '__|
# | (_| | (_) | (__|   <  __/ |   
#  \__,_|\___/ \___|_|\_\___|_|   


